name: CI

on: push

jobs:
  sast_scan:
    name: Bandit scan
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
            
      - name: install bandit
        run: pip install bandit 

      - name: run bandit
        run: bandit -r . -f json -o bandit_report.json
        
      - name: upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bandit_findings
          path: bandit_report.json
