name: CI

on: push

jobs:
  sast_scan:
    name: SAST - Bandit scan
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
            
      - name: install bandit
        run: pip install bandit 

      - name: run bandit
        run: bandit -ll -ii -r . -f html -o bandit_report.html # Apenas as falhas críticas e altas
        
      - name: upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit_findings
          path: bandit_report.html

          
  docker_image_scan:
    name: SCA - Docker scout scan
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup docker
        uses: docker-practice/actions-setup-docker@v1
        with: 
          docker_version: 28.0.1

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Docker scout scan 
        uses: docker/scout-action@v1.16.1
        with:
          dockerhub-user: ${{ secrets.REPO_USER }}
          dockerhub-password: ${{ secrets.REPO_PWD }}
          command: quickview,cves
          only-severities: critical,high # Apenas as falhas críticas e altas
          sarif-file: scout-report.sarif


  dast_scan:
    name: DAST - ZAP Scan
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Application and ZAP
        run: |
          docker network create zap-network
          docker-compose -f docker-compose.yml up -d
          
      - name: ZAP Scan
        run: |
          docker run --rm --network zap-network ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://myapp:8080

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: /zap/wrk/report.html

    
      
  
  
