name: CI

on: push

jobs:
  sast_scan:
    name: SAST - Bandit scan
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
    
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
            
      - name: install bandit
        run: pip install bandit 

      - name: run bandit
        run: bandit -ll -ii -r . -f html -o bandit_report.html # Apenas as falhas críticas e altas
        
      - name: upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit_findings
          path: bandit_report.html

          
  docker_image_scan:
    name: SCA - Docker scout scan
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup docker
        uses: docker-practice/actions-setup-docker@v1
        with: 
          docker_version: 28.0.1

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Docker scout scan 
        uses: docker/scout-action@v1.16.1
        with:
          dockerhub-user: ${{ secrets.REPO_USER }}
          dockerhub-password: ${{ secrets.REPO_PWD }}
          command: quickview,cves
          only-severities: critical,high # Apenas as falhas críticas e altas
          sarif-file: scout-report.sarif

  dast_scan:
    name: DAST - Zap scan
    runs-on: ubuntu-latest
    services:
      zap:
        image: 'ghcr.io/zaproxy/zaproxy:stable'
        options: --network my-network --detach
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start application
        run: |
          docker run --rm -d --name pygoat --network my-network -p 8080:8080 myapp:latest

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://pygoat:8080'
          cmd_options: '-a'
    
      
  
  
